declare const process: {
  env: {
    EXPO_PUBLIC_KAKAO_MAP_APP_KEY?: string;
    EXPO_PUBLIC_KAKAO_NATIVE_APP_KEY?: string;
    EXPO_PUBLIC_KAKAO_REST_API_KEY?: string;
    EXPO_PUBLIC_GOOGLE_ANDROID_CLIENT_ID?: string;
    EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID?: string;
    EXPO_PUBLIC_OAUTH_REDIRECT_URI?: string;
    EXPO_PUBLIC_SUPABASE_URL?: string;
    EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY?: string;
    EXPO_PUBLIC_SUPABASE_ANON_KEY?: string;
  };
};
